name: Kung Foodie
favicon: null
layout_spectrum: 0.6846010803710669
typography_spectrum: 0.7298878547735512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.17222338169813156
  lightness: 0.009518995182588696
  saturation: 0.7552895010448992
  rhythmicContrast: 0.22570243570953608
purpose: []
